backup_results: true
checkpoint_frequency: 5
cleanup_frequency: 5
cross_validation_folds: 5
early_stopping: true
early_stopping_patience: 10
enable_hardware_monitoring: true
gpu_memory_fraction: 0.8
max_duration_hours: 12.0
max_retries: 2
max_trials: 50
memory_limit_gb: null
min_improvement: 0.001
parallel_jobs: 1
random_seed: null
retry_failed_trials: false
save_intermediate_results: true
trial_timeout_minutes: 60.0
validation_split: 0.2
validation_strategy: holdout
